In [5]:
import numpy as np

In [8]:
grid = [[0,0,2,0,6,0,0,0,0],
        [3,0,0,0,0,9,0,0,0],
        [7,9,0,2,4,0,5,0,8],
        [0,4,9,1,0,8,0,0,0],
        [0,0,0,0,2,0,0,0,0],
        [0,0,0,4,0,3,7,9,0],
        [9,0,1,0,3,7,0,2,4],
        [0,0,0,8,0,0,0,0,6],
        [0,0,0,0,1,0,9,0,0]]

print(np.matrix(grid))

[[0 0 2 0 6 0 0 0 0]
 [3 0 0 0 0 9 0 0 0]
 [7 9 0 2 4 0 5 0 8]
 [0 4 9 1 0 8 0 0 0]
 [0 0 0 0 2 0 0 0 0]
 [0 0 0 4 0 3 7 9 0]
 [9 0 1 0 3 7 0 2 4]
 [0 0 0 8 0 0 0 0 6]
 [0 0 0 0 1 0 9 0 0]]


In [9]:
def possible(row,column,number):
    # Is the no. appears in given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False   
    
    # Is the no. appears in given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False  
    
    # Is the no.appears within the block?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False
            
    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] =number
                        solve()
                        grid[row][column]=0
                return 
            
    print(np.matrix(grid))
    
    
solve()
            
    

[[4 8 2 3 6 5 1 7 9]
 [3 1 5 7 8 9 6 4 2]
 [7 9 6 2 4 1 5 3 8]
 [5 4 9 1 7 8 2 6 3]
 [1 7 3 9 2 6 4 8 5]
 [6 2 8 4 5 3 7 9 1]
 [9 6 1 5 3 7 8 2 4]
 [2 5 7 8 9 4 3 1 6]
 [8 3 4 6 1 2 9 5 7]]


In [14]:
# Get an i/p of 9*9 matrix

r=9
c=9
grid =[]
for i in range(r):
    a=[]
    for j in range(c):
        k = int(input())
        a.append(k)
        
    grid.append(a)
    
for i in range(r):
    for j in range(c):
        print(grid[i][j], end =" ")
    print()
    

0
0
2
0
6
0
0
0
0
3
0
0
0
0
9
0
0
0
7
9
0
2
4
0
5
0
8
0
4
9
1
0
8
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
4
0
3
7
9
0
9
0
1
0
3
7
0
2
4
0
0
0
8
0
0
0
0
6
0
0
0
0
1
0
9
0
0
0 0 2 0 6 0 0 0 0 
3 0 0 0 0 9 0 0 0 
7 9 0 2 4 0 5 0 8 
0 4 9 1 0 8 0 0 0 
0 0 0 0 2 0 0 0 0 
0 0 0 4 0 3 7 9 0 
9 0 1 0 3 7 0 2 4 
0 0 0 8 0 0 0 0 6 
0 0 0 0 1 0 9 0 0 


In [19]:
def possible(row,column,number):
    # Is the no. appears in given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False   
    
    # Is the no. appears in given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False  
    
    # Is the no.appears within the block?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False
            
    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] =number
                        solve()
                        grid[row][column]=0
                return 
            
    print(np.matrix(grid))
    
    
solve()
            

[['0' '0' '9' '0' '5' '7' '4' '0' '0']
 ['0' '0' '5' '1' '0' '4' '2' '0' '0']
 ['0' '0' '0' '0' '2' '6' '0' '9' '5']
 ['1' '0' '0' '4' '0' '9' '0' '0' '0']
 ['3' '0' '0' '0' '7' '0' '0' '0' '0']
 ['0' '0' '7' '0' '0' '0' '0' '4' '0']
 ['9' '0' '1' '0' '0' '0' '0' '0' '0']
 ['0' '4' '0' '7' '0' '0' '0' '8' '9']
 ['7' '3' '2' '0' '4' '0' '0' '0' '0']]


In [18]:
## Create a sudoku puzzle

from dokusan import generators
import numpy as np

arr = np.array(list(str(generators.random_sudoku(avg_rank=150))))
grid = arr.reshape(9,9)
grid


array([['0', '0', '9', '0', '5', '7', '4', '0', '0'],
       ['0', '0', '5', '1', '0', '4', '2', '0', '0'],
       ['0', '0', '0', '0', '2', '6', '0', '9', '5'],
       ['1', '0', '0', '4', '0', '9', '0', '0', '0'],
       ['3', '0', '0', '0', '7', '0', '0', '0', '0'],
       ['0', '0', '7', '0', '0', '0', '0', '4', '0'],
       ['9', '0', '1', '0', '0', '0', '0', '0', '0'],
       ['0', '4', '0', '7', '0', '0', '0', '8', '9'],
       ['7', '3', '2', '0', '4', '0', '0', '0', '0']], dtype='<U1')

In [17]:
pip install dokusan

Note: you may need to restart the kernel to use updated packages.
